GET http://localhost:3000/subscribers

###
POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "riya",
    "subscribedToChannel":"rishi" 


}

###

http://localhost:3000/subscribers/6506e48f3229260768d41495